services:
  frontend:
    image: node:16.16-slim
    command: sh -c "npm ci && ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url='./'"
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend

  db-server:
    image: postgres:16.7-alpine3.21
    env_file:
      - ./.env_db
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

  backend:
    build: ./backend
    working_dir: /backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./frontend/bundles:/backend/bundles
    command: sh -c "python3 manage.py migrate && python3 manage.py collectstatic --clear --noinput && gunicorn -w 3 -b 0.0.0.0:8000 star_burger.wsgi:application"
    env_file:
      - ./.env
    depends_on:
      - db-server

volumes:
  db_volume: