# Generated by Django 4.2.9 on 2024-11-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_called_at_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой онлайн')], db_index=True, default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
