# Generated by Django 4.2.9 on 2024-11-19 18:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона')),
                ('delivery_address', models.TextField(max_length=200, verbose_name='Адрес доставки')),
                ('products', models.ManyToManyField(related_name='orders', to='foodcartapp.product', verbose_name='Состав заказа')),
            ],
        ),
    ]
