# Generated by Django 4.2.9 on 2024-11-23 15:06

from django.db import migrations


def fill_old_orders_prices(apps, schema_editor):
    OrderItem = apps.get_model("foodcartapp", "OrderItem")

    order_items = OrderItem.objects.filter(price=0).prefetch_related("product")
    for order_item in order_items.iterator():
        order_item.price = order_item.product.price
        order_item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0042_orderitem_price"),
    ]

    operations = [
        migrations.RunPython(fill_old_orders_prices),
    ]
